import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 0.9,
  },
  addDrugButton: {
    width: 170,
    backgroundColor: 'dodgerblue',
    padding: 10,
    margin: 15,
    marginBottom: 0,
    alignItems: 'center',
    borderWidth: 1,
    textShadowColor: 'black',
  },
  addDrugButtonDisabled: {
    width: 170,
    backgroundColor: 'dodgerblue',
    padding: 10,
    margin: 15,
    marginBottom: 0,
    alignItems: 'center',
    borderWidth: 1,
    textShadowColor: 'black',
    opacity: 0.3,
  },
  input: {
    width: 265,
    padding: 10,
    margin: 15,
    marginTop: 0,
    marginBottom: 0,
    height: 55,
    borderColor: 'black',
    borderWidth: 1,
  },
  Counterinput: {
    width: 100,
    padding: 10,
    margin: 15,
    marginBottom: 0,
    height: 40,
    borderColor: 'black',
    borderWidth: 1,
  },
  errorMessage: {
    color: 'red',
    textAlign: 'left',
    marginTop: 0,
    marginLeft: 12,
    marginBottom: 15,
  },
  Label: {
    color: 'black',
    textAlign: 'left',
    marginTop: 15,
    marginLeft: 12,
    marginBottom: 0,
  },
  datePicker: {
    width: 265,
    margin: 15,
    marginTop: 0,
    borderColor: 'black',
    borderWidth: 1,
    marginBottom: 0,
  },
  dateIcon: {
    position: 'relative',
    right: 0,
    top: 4,
    marginRight: 0,
  },
  setTimeButton: {
    position: 'relative',
    width: 50,
    height: 50,
    shadowRadius: 20,
  },
  footer: {
    position: 'absolute',
    flex: 0.1,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'white',
    height: 80,
    alignItems: 'center',
  },
  drugFrequencyView: {
    flexDirection: 'row',
    borderWidth: 1,
    width: 265,
    height: 55,
    padding: 10,
    margin: 15,
    marginTop: 0,
    marginBottom: 0,
    alignItems: 'center',
  },
  counterInputStyles: {
    width: 80,
    height: 3,
    left: 170,
    position: 'absolute',
  },
  mainView: { flex: 1 },
  buttonText: { fontWeight: 'bold' },
  bodyAlignment: { flexDirection: 'row' },
});

export default styles;
