import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  item: {
    backgroundColor: 'teal',
  },
  input: {
    width: 240,
    padding: 10,
    height: 35,
    marginLeft: 30,
    marginTop: 20,
    borderColor: 'black',
    borderWidth: 1,
    alignItems: 'center',
  },
  submitButton: {
    width: 100,
    backgroundColor: '#848482',
    padding: 10,
    margin: 15,
    height: 40,
    alignItems: 'center',
  },
  cardbutton: {
    width: 40,
    backgroundColor: '#FF8C00',
    height: 20,
    borderColor: 'black',
    borderWidth: 1,
    marginRight: '5%',
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    opacity: 0.5,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  prescriptionNotFoundText: {
   color: 'grey',
   marginTop: '50%',
   marginLeft: 130,
  },
  viewButton: {
    backgroundColor: '#f0ffff',
    borderColor: 'black',
    borderWidth: 1,
    width: 50,
    marginRight: '5%',
    alignItems: 'center',
  },
  deleteButton: {
    backgroundColor: 'indianred',
    borderColor: 'black',
    borderWidth: 1,
    width: 50,
    alignItems: 'center',
  },
  newPrescription: {
    width: 200,
    backgroundColor: 'dodgerblue',
    padding: 10,
    margin: 15,
    alignItems: 'center',
  },
  footer: {
    position: 'absolute',
    flex: 0.1,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'white',
    height: 80,
    alignItems: 'center',
  },
  cardTextView: { color: 'teal', fontWeight: 'bold' },
  cardText: { marginRight: '20%', marginLeft: '20%' },
  viewTextButton: { fontWeight: 'bold' },
  mainView: { flex: 1 },
  bodyView: { flex: 0.9 },
  buttonAlignment: { flexDirection: 'row' },
});
export default styles;
